### ISSUE TITLE
Enable discussions

### ISSUE THREAD

**Issue by winksaville** [ferrous-systems/testing-proc-macros#3]
I'd like to suggest that github discussions be enabled or maybe there is some other forum where questions can be asked?

**Comment by japaric** [comment]
thanks for the suggestion. in general, we don't use GitHub discussions in the open source projects we maintain. as this is a repo with sample code I don't think a GitHub discussions space would see much participation; I can, however, recommend the Rust users forum and the rust-lang discord server as ways to engage with the broad community -- see https://www.rust-lang.org/community for links to those spaces.

There's also Ferrous Systems' [rust-experts](https://ferrous-systems.com/rust-experts/) service if you would like to tap into our expertise.
